version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: blood_donation_db_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blood_donation_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 5s
      retries: 5
      interval: 10s

  backend_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blood_donation_backend
    ports:
      - "8080:8080"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_NAME=blood_donation_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - JAVA_TOOL_OPTIONS=-Xmx512m -XX:+UseSerialGC

volumes:
  mysql_data:
